import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{Search,SlidersHorizontal,ArrowUpRight,AudioLines,Activity,Image as ImageIcon,ScanLine,Clock3,X,Database,ChevronDown,ArrowRight}from'lucide-react';import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
function App(){const [query,setQuery]=useState(''),[model,setModel]=useState('vector'),[modality,setModality]=useState('all'),[topK,setTopK]=useState(10),[results,setResults]=useState([]),[total,setTotal]=useState(0),[stats,setStats]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[searched,setSearched]=useState(false),[selected,setSelected]=useState(null),[history,setHistory]=useState(()=>JSON.parse(localStorage.getItem('autism-ir-history')||'[]'));
useEffect(()=>{fetch(`${API}/dataset/stats`).then(r=>r.json()).then(setStats).catch(()=>setError('Search API is unavailable. Start the backend and try again.'))},[]);
async function search(q=query){if(!q.trim()){setError('Enter a query to search the dataset.');return}setBusy(true);setError('');setQuery(q);setSearched(true);try{const r=await fetch(`${API}/search/${model==='vector'?'vector':'boolean'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,modality,top_k:topK})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Search failed.');setResults(data.results);setTotal(data.total_results);const next=[q,...history.filter(x=>x!==q)].slice(0,5);setHistory(next);localStorage.setItem('autism-ir-history',JSON.stringify(next))}catch(e){setError(e.message)}finally{setBusy(false)}}
const modalities=stats?.available_modalities||['image','motion','physio','voice'];const icons={image:ImageIcon,voice:AudioLines,motion:ScanLine,physio:Activity};
return <main><nav className="nav"><div className="brand"><span className="brand-mark"><Activity size={19}/></span><span>signal<span className="brand-light">/search</span></span></div><div className="nav-right"><span className="live-dot"/>LOCAL DATASET <span className="nav-divider"/> IR LAB</div></nav>
<section className="hero"><div className="eyebrow"><span/> INFORMATION RETRIEVAL · MULTIMODAL DATA</div><h1>Find the signals<br/><i>in every sample.</i></h1><p className="intro">Search across 100 autism research samples with classical Boolean retrieval and TF-IDF ranking.</p>
<form className="search-box" onSubmit={e=>{e.preventDefault();search()}}><Search size={21}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try “child eye gaze autism”" aria-label="Search dataset"/><button type="submit" disabled={busy}>{busy?'Searching':'Search'} <ArrowRight size={16}/></button></form>
<div className="controls"><div className="control-label"><SlidersHorizontal size={14}/> SEARCH CONFIGURATION</div><div className="control-row"><div className="segmented"><button className={model==='vector'?'active':''} onClick={()=>setModel('vector')} type="button">Vector Space</button><button className={model==='boolean'?'active':''} onClick={()=>setModel('boolean')} type="button">Boolean</button></div><label>MODALITY<select value={modality} onChange={e=>setModality(e.target.value)}><option value="all">All modalities</option>{modalities.map(m=><option key={m} value={m}>{m[0].toUpperCase()+m.slice(1)}</option>)}</select><ChevronDown size={13}/></label>{model==='vector'&&<label>TOP RESULTS<select value={topK} onChange={e=>setTopK(+e.target.value)}>{[5,10,20,50].map(n=><option key={n}>{n}</option>)}</select><ChevronDown size={13}/></label>}<span className="model-note">{model==='vector'?'TF–IDF · COSINE SIMILARITY':'INVERTED INDEX · BOOLEAN'}</span></div></div></section>
<section className="workspace">{stats&&<div className="stats-strip"><div className="stats-title"><Database size={16}/><span>DATASET AT A GLANCE</span></div><div><b>{stats.total_documents}</b><small>samples</small></div>{Object.entries(stats.modalities).map(([m,n])=><div key={m}><b>{n}</b><small>{m}</small></div>)}<div className="labels">{stats.labels?.map(l=><span key={l}>{l.replace('_',' ')}</span>)}</div></div>}
<div className="results-head"><div><div className="section-kicker">{searched?'RETRIEVAL RESULTS':'EXPLORE THE COLLECTION'}</div><h2>{searched?<>Results <span>({total})</span></>:'Search the dataset'}</h2></div>{searched&&<button className="clear-btn" onClick={()=>{setQuery('');setResults([]);setSearched(false);setError('')}}><X size={14}/> Clear search</button>}</div>
{error&&<div className="error">{error}</div>}{busy&&<div className="loading"><span/> Ranking documents with {model==='vector'?'TF–IDF cosine similarity':'the inverted index'}…</div>}
{!searched&&!busy&&<div className="discovery"><div className="discover-copy"><span className="micro">START WITH A QUERY</span><p>Explore labels, descriptions, and modality availability across the collection.</p></div><div className="suggestions">{['autism AND mild','typical OR moderate','autism AND voice','severe_asd'].map(x=><button key={x} onClick={()=>search(x)}>{x}<ArrowUpRight size={14}/></button>)}</div></div>}
{searched&&!busy&&results.length===0&&!error&&<div className="empty"><Search size={25}/><h3>No matching samples</h3><p>Try broader terms or switch the modality filter to All.</p></div>}
<div className="cards">{results.map((d,i)=>{const img=d.files?.image,Icon=icons[modality]||Database;return <article className="result-card" key={d.document_id}><div className="result-top"><span className="ordinal">{String(i+1).padStart(2,'0')}</span><div className="result-name"><h3>{d.document_id}</h3><span>{d.label?.replace('_',' ')||'Sample'} · {d.metadata?.severity||'severity unavailable'}</span></div><span className="modality-badge"><Icon size={13}/>{modality==='all'?'MULTIMODAL':modality.toUpperCase()}</span></div><p className="description">{d.description}</p>{d.score!==undefined?<div className="score-row"><div><span>SIMILARITY</span><b>{(d.score*100).toFixed(1)}%</b></div><div className="meter"><i style={{width:`${Math.min(d.score*100,100)}%`}}/></div></div>:<div className="matched"><span>MATCHED TERMS</span>{d.matched_terms?.map(t=><em key={t}>{t} ✓</em>)}</div>}
<div className="tag-row">{(d.keywords||[]).slice(0,5).map(t=><span key={t}>{t}</span>)}</div><div className="card-footer"><div className="fileline"><span>{d.files?.image?.filename||'No image file'}</span><small>{d.files?.image?.indexed_path||'Image path unavailable'}</small></div><button className="open-btn" onClick={()=>setSelected(d)}>View record <ArrowUpRight size={15}/></button></div></article>})}</div>
{history.length>0&&<div className="history"><div className="section-kicker"><Clock3 size={13}/> RECENT SEARCHES</div>{history.map(h=><button key={h} onClick={()=>search(h)}>{h}<ArrowUpRight size={13}/></button>)}</div>}
<footer><span>CLASSICAL INFORMATION RETRIEVAL</span><span>BOOLEAN + TF–IDF VECTOR SPACE</span><span>100 SAMPLE DOCUMENTS</span></footer></section>
{selected&&<div className="overlay" onClick={()=>setSelected(null)}><section className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}><X/></button><div className="section-kicker">SAMPLE RECORD</div><h2>{selected.document_id}</h2><p>{selected.description}</p>{selected.files?.image?.exists&&<img className="preview" src={`${API}/file/${selected.document_id}/image`} alt={`Image for ${selected.document_id}`}/>}<div className="modal-files">{Object.entries(selected.files||{}).map(([m,f])=><div key={m}><span>{m}</span>{f.exists?<>{m==='voice'?<audio controls src={`${API}/file/${selected.document_id}/${m}`}/>:<a href={`${API}/file/${selected.document_id}/${m}`} target="_blank" rel="noreferrer">{f.filename} ↗</a>}</>:<small>Not available on disk</small>}<small className="source-path">Index: {f.indexed_path||'none'}{f.indexed_path&&f.path&&f.indexed_path!==f.path&&` · resolved: ${f.filename}`}</small></div>)}</div><pre>{JSON.stringify(selected.metadata,null,2)}</pre></section></div>}</main>}
createRoot(document.getElementById('root')).render(<App/>);
