import React, { useEffect, useState } from 'react'; import { createRoot } from 'react-dom/client'; import { Search, SlidersHorizontal, ArrowUpRight, AudioLines, Activity, Image as ImageIcon, ScanLine, Clock3, X, Database, ChevronDown, ArrowRight } from 'lucide-react'; import './style.css'; import './theme.css';
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
function App() {
    const [query, setQuery] = useState(''), [model, setModel] = useState('vector'), [resultsModel, setResultsModel] = useState('vector'), [page, setPage] = useState(window.location.hash === '#structured' ? 'structured' : 'unstructured'), [modality, setModality] = useState('all'), [topK, setTopK] = useState(10), [results, setResults] = useState([]), [total, setTotal] = useState(0), [stats, setStats] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [searched, setSearched] = useState(false), [selected, setSelected] = useState(null), [relevantIds, setRelevantIds] = useState([]), [nonRelevantIds, setNonRelevantIds] = useState([]), [history, setHistory] = useState(() => JSON.parse(localStorage.getItem('autism-ir-history') || '[]'));
    const modelGroups = {
        unstructured: [
            ['boolean', 'Boolean'], ['vector', 'Vector Space'],
            ['probabilistic', 'Query Likelihood'], ['bim', 'BIM'], ['bm25', 'BM25'],
        ],
        structured: [
            ['overlap_lists', 'Overlap Lists'], ['non_overlap_lists', 'Non-Overlap Lists'],
            ['proximal_nodes', 'Proximal Nodes'],
        ],
    };
    useEffect(() => {
        const syncPage = () => {
            const nextPage = window.location.hash === '#structured' ? 'structured' : 'unstructured';
            setPage(nextPage);
            setModel(nextPage === 'structured' ? 'overlap_lists' : 'vector');
            setResults([]); setTotal(0); setSearched(false); setError('');
            setRelevantIds([]); setNonRelevantIds([]);
        };
        window.addEventListener('hashchange', syncPage);
        return () => window.removeEventListener('hashchange', syncPage);
    }, []);
    useEffect(() => { fetch(`${API}/dataset/stats`).then(r => r.json()).then(setStats).catch(() => setError('Search API is unavailable. Start the backend and try again.')) }, []);
    async function search(q = query, judgedRelevant = relevantIds, judgedNonRelevant = nonRelevantIds) { if (!q.trim()) { setError('Enter a query to search the dataset.'); return } setBusy(true); setError(''); setQuery(q); setSearched(true); try { const endpoint = model === 'boolean' ? 'boolean' : model === 'probabilistic' ? 'probabilistic' : model === 'bim' ? 'bim' : model === 'bm25' ? 'bm25' : model === 'overlap_lists' ? 'overlap-lists' : model === 'non_overlap_lists' ? 'non-overlap-lists' : model === 'proximal_nodes' ? 'proximal-nodes' : 'vector'; const payload = { query: q, modality, top_k: topK }; if (model === 'bim') { payload.relevant_ids = judgedRelevant; payload.non_relevant_ids = judgedNonRelevant } const r = await fetch(`${API}/search/${endpoint}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await r.json(); if (!r.ok) throw new Error(data.detail || 'Search failed.'); setResults(data.results); setResultsModel(model); setTotal(data.total_results); const next = [q, ...history.filter(x => x !== q)].slice(0, 5); setHistory(next); localStorage.setItem('autism-ir-history', JSON.stringify(next)) } catch (e) { setError(e.message) } finally { setBusy(false) } }
    function markFeedback(documentId, isRelevant) { const selectedIds = isRelevant ? relevantIds : nonRelevantIds; const nextRelevant = relevantIds.filter(id => id !== documentId); const nextNonRelevant = nonRelevantIds.filter(id => id !== documentId); if (!selectedIds.includes(documentId)) (isRelevant ? nextRelevant : nextNonRelevant).push(documentId); setRelevantIds(nextRelevant); setNonRelevantIds(nextNonRelevant); search(query, nextRelevant, nextNonRelevant); }
    const modalities = stats?.available_modalities || ['image', 'motion', 'physio', 'voice']; const icons = { image: ImageIcon, voice: AudioLines, motion: ScanLine, physio: Activity }; const availableModels = modelGroups[page];
    return <main><nav className="nav"><div className="brand"><span className="brand-mark"><Activity size={19} /></span><span>signal<span className="brand-light">/search</span></span></div><div className="page-nav"><a href="#unstructured" className={page === 'unstructured' ? 'active' : ''}>Unstructured Models</a><a href="#structured" className={page === 'structured' ? 'active' : ''}>Structured Models</a></div><div className="nav-right"><span className="live-dot" />LOCAL DATASET <span className="nav-divider" /> IR LAB</div></nav>
        <section className="hero"><div className="eyebrow"><span /> INFORMATION RETRIEVAL · {page === 'structured' ? 'STRUCTURED RETRIEVAL' : 'UNSTRUCTURED RETRIEVAL'}</div><h1>{page === 'structured' ? <>Search within<br /><i>document structure.</i></> : <>Find the signals<br /><i>in every sample.</i></>}</h1><p className="intro">{page === 'structured' ? 'Compare region-based retrieval with nested fields, disjoint lists, and term proximity.' : 'Search across 100 autism research samples with Boolean, TF-IDF, BIM, BM25, and query-likelihood models.'}</p>
            <form className="search-box" onSubmit={e => { e.preventDefault(); search() }}><Search size={21} /><input value={query} onChange={e => { setQuery(e.target.value); setRelevantIds([]); setNonRelevantIds([]) }} placeholder="Try “child eye gaze autism”" aria-label="Search dataset" /><button type="submit" disabled={busy}>{busy ? 'Searching' : 'Search'} <ArrowRight size={16} /></button></form>
            <div className="controls"><div className="control-label"><SlidersHorizontal size={14} /> SEARCH CONFIGURATION</div><div className="control-row"><div className="segmented">{availableModels.map(([key, label]) => <button key={key} className={model === key ? 'active' : ''} onClick={() => setModel(key)} type="button">{label}</button>)}</div><label>MODALITY<select value={modality} onChange={e => { setModality(e.target.value); setRelevantIds([]); setNonRelevantIds([]) }}><option value="all">All modalities</option>{modalities.map(m => <option key={m} value={m}>{m[0].toUpperCase() + m.slice(1)}</option>)}</select><ChevronDown size={13} /></label>{model !== 'boolean' && <label>TOP RESULTS<select value={topK} onChange={e => setTopK(+e.target.value)}>{[5, 10, 20, 50].map(n => <option key={n}>{n}</option>)}</select><ChevronDown size={13} /></label>}<span className="model-note">{model === 'vector' ? 'TF–IDF · COSINE' : model === 'probabilistic' ? 'QUERY LIKELIHOOD' : model === 'bim' ? 'BINARY TERM PRESENCE · RSJ WEIGHTS' : model === 'bm25' ? 'TERM FREQUENCY · IDF · LENGTH NORM' : model === 'overlap_lists' ? 'NESTED RECORD + FIELD REGIONS' : model === 'non_overlap_lists' ? 'DISJOINT FIELD REGIONS' : model === 'proximal_nodes' ? 'HIERARCHY + TERM PROXIMITY' : 'INVERTED INDEX · BOOLEAN'}</span></div>{model === 'bim' && <p className="bim-help">BIM starts with collection-based estimates. Mark results relevant or not relevant to provide feedback and rerank.</p>}{(model === 'overlap_lists' || model === 'non_overlap_lists') && <p className="bim-help">{model === 'overlap_lists' ? 'Searches nested sample and metadata-field regions.' : 'Searches each metadata field as a separate, disjoint region.'} Results show matched fields; field coverage is an explanatory ordering, not a probability.</p>}{model === 'proximal_nodes' && <p className="bim-help">Indexes the record, metadata fields, and description sentences as parent-child nodes. Results favor query terms found close together in one node.</p>}</div></section>
        <section className="workspace">{stats && <div className="stats-strip"><div className="stats-title"><Database size={16} /><span>DATASET AT A GLANCE</span></div><div><b>{stats.total_documents}</b><small>samples</small></div>{Object.entries(stats.modalities).map(([m, n]) => <div key={m}><b>{n}</b><small>{m}</small></div>)}<div className="labels">{stats.labels?.map(l => <span key={l}>{l.replace('_', ' ')}</span>)}</div></div>}
            <div className="results-head"><div><div className="section-kicker">{searched ? 'RETRIEVAL RESULTS' : 'EXPLORE THE COLLECTION'}</div><h2>{searched ? <>Results <span>({total})</span></> : 'Search the dataset'}</h2></div>{searched && <button className="clear-btn" onClick={() => { setQuery(''); setResults([]); setSearched(false); setError('') }}><X size={14} /> Clear search</button>}</div>
            {error && <div className="error">{error}</div>}{busy && <div className="loading"><span /> Ranking documents with {model === 'vector' ? 'TF–IDF cosine similarity' : model === 'probabilistic' ? 'query likelihood probabilities' : model === 'bim' ? 'Binary Independence Model' : model === 'bm25' ? 'BM25' : model === 'proximal_nodes' ? 'Proximal Nodes' : model === 'overlap_lists' || model === 'non_overlap_lists' ? 'structured region lists' : 'the inverted index'}…</div>}
            {!searched && !busy && <div className="discovery"><div className="discover-copy"><span className="micro">START WITH A QUERY</span><p>Explore labels, descriptions, and modality availability across the collection.</p></div><div className="suggestions">{['autism AND mild', 'typical OR moderate', 'autism AND voice', 'severe_asd'].map(x => <button key={x} onClick={() => search(x, [], [])}>{x}<ArrowUpRight size={14} /></button>)}</div></div>}
            {searched && !busy && results.length === 0 && !error && <div className="empty"><Search size={25} /><h3>No matching samples</h3><p>Try broader terms or switch the modality filter to All.</p></div>}
            <div className="cards">{results.map((d, i) => {
                const img = d.files?.image, Icon = icons[modality] || Database; const isListModel = resultsModel === 'overlap_lists' || resultsModel === 'non_overlap_lists'; const isProximalModel = resultsModel === 'proximal_nodes'; return <article className="result-card" key={d.document_id}><div className="result-top"><span className="ordinal">{String(i + 1).padStart(2, '0')}</span><div className="result-name"><h3>{d.document_id}</h3><span>{d.label?.replace('_', ' ') || 'Sample'} · {d.metadata?.severity || 'severity unavailable'}</span></div><span className="modality-badge"><Icon size={13} />{modality === 'all' ? 'MULTIMODAL' : modality.toUpperCase()}</span></div><p className="description">{d.description}</p>{d.score !== undefined ? <div className="score-row"><div><span>{resultsModel === 'probabilistic' ? 'P(DOC | QUERY)' : resultsModel === 'bim' ? 'RSJ WEIGHT' : resultsModel === 'bm25' ? 'BM25 SCORE' : isListModel ? 'MATCHED FIELD REGIONS' : isProximalModel ? 'PROXIMITY SCORE' : 'SIMILARITY'}</span><b>{resultsModel === 'bim' || resultsModel === 'bm25' || isProximalModel ? d.score.toFixed(3) : isListModel ? d.region_match_count : `${(d.score * 100).toFixed(1)}%`}</b></div>{resultsModel !== 'bim' && resultsModel !== 'bm25' && !isListModel && !isProximalModel && <div className="meter"><i style={{ width: `${Math.min(d.score * 100, 100)}%` }} /></div>}</div> : <div className="matched"><span>MATCHED TERMS</span>{d.matched_terms?.map(t => <em key={t}>{t} ✓</em>)}</div>}{isListModel && <div className="matched"><span>MATCHED REGIONS</span>{d.matched_regions?.map(region => <em key={region}>{region}</em>)}</div>}{isProximalModel && <div className="matched"><span>BEST NODE · PARENT · WINDOW</span><em>{d.proximity_node} · {d.proximity_parent || 'root'} · {d.proximity_window ?? 'n/a'} tokens</em></div>}{model === 'bim' && resultsModel === 'bim' && <div className="feedback-actions"><button className={relevantIds.includes(d.document_id) ? 'selected' : ''} onClick={() => markFeedback(d.document_id, true)} type="button">Relevant</button><button className={nonRelevantIds.includes(d.document_id) ? 'selected negative' : ''} onClick={() => markFeedback(d.document_id, false)} type="button">Not relevant</button></div>}
                    <div className="tag-row">{(d.keywords || []).slice(0, 5).map(t => <span key={t}>{t}</span>)}</div><div className="card-footer"><div className="fileline"><span>{d.files?.image?.filename || 'No image file'}</span><small>{d.files?.image?.indexed_path || 'Image path unavailable'}</small></div><button className="open-btn" onClick={() => setSelected(d)}>View record <ArrowUpRight size={15} /></button></div></article>
            })}</div>
            {history.length > 0 && <div className="history"><div className="section-kicker"><Clock3 size={13} /> RECENT SEARCHES</div>{history.map(h => <button key={h} onClick={() => search(h, [], [])}>{h}<ArrowUpRight size={13} /></button>)}</div>}
            <footer><span>CLASSICAL INFORMATION RETRIEVAL</span><span>BOOLEAN + TF–IDF + BIM + BM25 + STRUCTURED REGION LISTS</span><span>100 SAMPLE DOCUMENTS</span></footer></section>
        {selected && <div className="overlay" onClick={() => setSelected(null)}><section className="modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)}><X /></button><div className="section-kicker">SAMPLE RECORD</div><h2>{selected.document_id}</h2><p>{selected.description}</p>{selected.files?.image?.exists && <img className="preview" src={`${API}/file/${selected.document_id}/image`} alt={`Image for ${selected.document_id}`} />}<div className="modal-files">{Object.entries(selected.files || {}).map(([m, f]) => <div key={m}><span>{m}</span>{f.exists ? <>{m === 'voice' ? <audio controls src={`${API}/file/${selected.document_id}/${m}`} /> : <a href={`${API}/file/${selected.document_id}/${m}`} target="_blank" rel="noreferrer">{f.filename} ↗</a>}</> : <small>Not available on disk</small>}<small className="source-path">Index: {f.indexed_path || 'none'}{f.indexed_path && f.path && f.indexed_path !== f.path && ` · resolved: ${f.filename}`}</small></div>)}</div><pre>{JSON.stringify(selected.metadata, null, 2)}</pre></section></div>}</main>
}
createRoot(document.getElementById('root')).render(<App />);
